from turtle import *
speed(7)
def y(radius,color1,color2):
    width(3)
    color("black",color1)
    begin_fill()
    circle(radius/2,180)
    circle(radius,180)
    left(180)
    circle(-radius/2,180)
    end_fill()
    left(90)
    up()
    forward(radius*0.35)
    right(90)
    down()
    color(color1,color2)
    begin_fill()
    circle(radius*0.15)
    end_fill()
    left(90)
    up()
    backward(radius*0.35)
    down()
    left(90)
    
y(500,"black","white")
y(500,"white","black")
